- docs/carpet/script/CarpetExpression.html
> Making the `run` command documentation more explicit

- programs/fundamentals/README.md
- programs/simulations/README.md
- programs/survival/README.md
- programs/survival/signs_for_water_streams.sc
- programs/utilities/README.md
Added signs_for_water_streams - skips the message entry prompt when a bucket is in the offhand
Added readmes to most of the apps folders, not entirely sure how accurate they are, just tried to open up the apps and generalize them a bit into a category
> Adding one survival app, and adding readmes to most of the apps folders

- programs/survival/revive_coral
By: Ghoulboy (that name was taken)
This is a script with enables the making of a coral block farm with carpet mod's `renewableCorals` set to `true`
> Reviving corals with water bottles

- programs/survival/easier_renewable_sponge.sc
There is no rng manipulation as far as I know, so sponge farms are near impossible to make useful
By:Ghoulboy
> Easier renewable sponge farm in 1.14+

- programs/survival/README.md
For now on, please add your scarpet app to this file with proper indentation and spacing so everyone can read it. This will be useful for those who want to quickly flick through and select some scripts without having to read the entire code to understand it
> Improved README.md to have decription of all scarpet apps

- programs/survival/easier_renewable_sponge.sc
Thanks to help, and because gnembon had told me to do it earlier
> Made the whole program more efficient

- docs/carpet/script/Expression.html
- programs/survival/signs_for_water_streams.sc
rewrite with suggestions from gnembon, adding check for storage blocks to allow normal sign placement, adding config section.
> Updating signs_for_water_streams

- programs/survival/README.md
I added proper styling for app names, creator names, then a creator list for those who wanted to know who something.
Also, I added clear instructions at the top.
> Improved README.md from the garbled mess that it was before

- programs/survival/README.md
- programs/survival/locate_block.sc
- programs/survival/shear_corals.sc
- programs/survival/very_basic_overworld_wither_cage_finder.sc
added shear_corals.sc Readme and the script itself(I hope)
> Added a load of programs

- programs/fundamentals/math.sc
It utilises Euclid's lemma to calculate, and for lcm its also easy, just divide product of two nums by hcf
> Added hcf and lcm to math.sc

- CONTRIBUTING.md
- programs/survival/README.md
Removed previous contributing guidelines from elsewhere cos theyre useless
> Added contributing.md

- README.md
- programs/survival/README.md
- programs/survival/cam.sc
- programs/survival/speed.sc
pls ignore first few commits, im bad at using github
> add cam and speed app

- programs/utilities/README.md
- programs/utilities/lifetimes
to measure mob lifetimes in a nice and user-friendly way
> Added lifetimes.sc

- programs/survival/cam.sc
Fixed an issue where leaving spectator would not return you to your original dimension.
> Update cam to work between dimensions

- programs/survival/README.md
(Sorry I am a pedant). Done based on my understanding of the apps. (May want to review to check correct).
Includes changing description of silk_spawners.sc for #113 (netherite pick).
> Corrected English/Clarified things

- programs/survival/cam.sc
> Prevent cam.sc from unloading after startup

- programs/survival/auto_lighter.sc
Cos then if you went into spec afer starting, it would not make u lose any torches. Now that val is set before you start.
And you can't cheat it by starting in spectator either. U simply can't start it in spectator, tho u can continue it in spec
> Changed auto_lighter.sc to make it so you can't cheat it by going into spectator

- programs/survival/README.md
- programs/survival/vacuum.sc
Improvements described in most recent commit (34108cc)
> Optimized vacuum.sc using gnembon's suggestions

- programs/survival/README.md
- programs/survival/sleep_ignore_fake_players.sc
completely rewritten
#136 gnembon/fabric-carpet#425
Fix the problem that can only be reset to day 1
Now it will not check the player's sleep every tick More efficient
All behave more like Vanilla
thx gnembon's suggest
> All true players sleeping Fixed!

- programs/survival/README.md
- programs/survival/rope_ladders.sc
- programs/survival/silk_blockstates.sc
- programs/survival/vines_instant_mine.sc
- programs/utilities/give_head.sc
- programs/utilities/gm.sc
- programs/utilities/sidebar.sc
**Survival Scripts Added:**
rope_ladders.sc
silk_blockstates.sc
vines_instant_mine.sc
**UtilitiesScripts Added:**
give_head.sc
gm.sc
sidebar.sc
> Added some BisUmTo survival and utilities scripts

- programs/survival/README.md
- programs/survival/destructive_lightning.sc
Once you start it any lightning that strikes, either natural, summoned or a channeling trident, a TNT and fireball will be summoned to create a small crater where the lightning strikes.
> Added destructive_lightning.sc

- README.md
https://github.com/replaceitem/scarpet-language-atom
> Added my Atom Scarpet package to Editor support in README

- programs/creative building tools/README.md
- programs/creative building tools/curves.sc
- programs/creative building tools/shapes.sc
Added another tool, now that it's somewhat finished. Also updated the curves app with a new shape.
> Building tools

- programs/survival/README.md
- programs/survival/nether_poi.sc
Just a simple nether point of interest renderer tool, useful when debugging some things.
> Nether poi viewer

- programs/survival/README.md
- programs/survival/signs_for_water_streams.sc
* Update to carpet 1.4.15
* Do not use sign items in creative
* Make it work with most mods/datapack sign types
> Signs for water streams updated for 1.4.15

- programs/survival/nopickup.sc
Fixed bug where every player would be assigned UUID "null".
Sorry gnembon :P
> Bug fix for nopickup.sc

- programs/survival/holy_hand_grenades.sc
Im not sure whether or not to add a check to see if the overall speed is more than a given speed, in which case to reduce to fixed value, so as not to make it too fast.
On the other hand, the given test subject is not exactly know for realism...
> Making it more realistic by taking into account hardness of block to apply velocity.

- programs/survival/README.md
- programs/survival/carried_totem.sc
Short script to mitigate the hand-icap of Totem of Undying (e.g. Hardcore world)
> Add carried_totem.sc to survival

- programs/survival/README.md
- programs/survival/horse_stats.sc
/horse_stats prints the 3 attributes of the targeted steed
> Add horse_stats.sc to survival

- programs/survival/README.md
- programs/survival/eyeremover.sc
CCF_100 mentioned on the discord that carpet should allow for the removal of eyes of ender from end portal frames to make getting to the End possible in peaceful.
> Added eyeremover.sc script for removing eyes of ender in peaceful

- programs/utilities/sidebar.sc
Added autocomplete scoreboard names.
Requested by antigravity.
> Reworte sidebar.sc with the new command system

- programs/survival/simply_harvest.sc
**Survival Scripts Added:**
simply_harvest
> Adding the 'simply_harvest' script

- programs/survival/silk_blockstates.sc
Using native `block_state()` function
> Updated to Scarpet 1.4.20

- programs/survival/simply_harvest.sc
> Fixed a bug reported by Bisumto

- programs/utilities/sidebar.sc
Sorry for the oversight...
I forgot to update the required version
> Updated required carpet version of sidebar.sc

- programs/survival/signs_for_water_streams.sc
> Fix Signs for water streams

- programs/utilities/camera.sc
I made #187 to remove the script, but then @BisUmTo said we should just update it. I will keep both PRs open and you can choose which to merge.
> Update camera.sc compared to Fabric Carpet (alternative to #187)

- programs/creative building tools/README.md
- programs/simulations/README.md
- programs/survival/README.md
Minor spelling corrections and updated description for angel blocks, villager poi, replace inventory and magic doors.
> Fix some spelling mistakes in READMEs and add missing descriptions

- programs/survival/villager_poi.sc
The memories NBT layout has changed. I tested the fix locally with 1.16.5
> fix villager_poi.sc for 1.16.5

- programs/README.md
Given that the folder got featured in the latest Carpet release notes, and that I felt like it needed it, I created a small `README` for the programs folder, basically showing the summary of the different categories and a note to encourage people to PR their apps.
> Created a README for the programs folder

- programs/survival/waypoints.sc
This app's development is being tracked in https://github.com/boyenn/scarpet-scripts. Changelog would read something like:
* Configurable track lines (thickness, angle, length)
* Bugfix: Appropiate dimension support.
> Fixed a few bugs, implemented  afew features

- programs/survival/README.md
- programs/survival/silk_budding_amethyst.sc
add silk touch for budding amethyst script
also cleanup a bunch of whitespace in the survival readme apparently
> add silk touch budding amethyst script

- programs/survival/simply_harvest.sc
> removed chat output from simply_harvest

- programs/simulations/sequential_mandelbrot_painter.sc
Just what the title says. It was a one line change. Though I also removed the superfluous empty first line.
> Fix mandelbrot_segment() definition to properly render entire canvas.

- programs/survival/hammer.sc
- programs/survival/veinminer.sc
This allows them to interface with `auto_pickup.sc`, which I've found is immensely helpful, seen as though these apps would tend to be used together.
> Add player breaks event call to hammer and veinminer

- programs/survival/README.md
- programs/survival/potion_master_cleric.sc
Adds 6 randomized potion trades to the cleric.
> Potion Master Cleric Script

- programs/survival/carried_totem.sc
submitting pr again due to old pr #261 was from master branch
This pull request is an attempt to fix #256  , and added autoload back.
Suggestions and contribution are much appreciated.
> fix carried_totem.sc "false alarm" issues, new pr

- programs/survival/playerme.sc
Fix the authors of playerme.sc
> AuthorsFix

- README.md
> Add a link to programs in the README

- programs/utilities/sscoreboard.sc
functions are described in the comments
> add sscoreboard app

- programs/survival/auto_lighter.sc
I added it as a global variable so you can change based on the version you're playing on. Should I use system_info to check automatically though?
I also added a boolean for lighting the ground cos some people want that too.
> Updated auto_ligher.sc to new 1.18+ light level

- programs/survival/auto_lighter.sc
Fixes #317 
This time I actually tested it thoroughly.
> Making auto_lighter finally light the ground

- programs/survival/eyeremover.sc
> Add sound to eye remover

- programs/building/cover.sc
> Fix typo in `cover.sc`

- programs/utilities/keepalive.sc
Found this when I was investigating #247
> Preserving players flying state when reloading in keepalive.sc

- programs/survival/signs_for_water_streams.sc
Fixes #184 
As altrisi mentioned, in #182 I managed to take out two commits, which properly depleted the player's hand stock.
> Added my changes to correct signs for water streams

- programs/survival/shulkerboxes.sc
> Make `shulkerboxes.sc` restock totems

- programs/survival/simply_harvest.sc
> Prevent `simply_harvest.sc` from using up blocks in either hand

- programs/survival/sneak_grow_overpowered.sc
Fixes #354.
This PR is intended to be *Rebase and merged*, given it includes a (very) backwards compatible way in the first commit, and a more general but modern one in the second one.
I think the second one is a good idea given it allows usage in custom and modded dimensions.
It'd probably be better to make it use sneak events that are dimension local, but that's for later.
> Fix deprecations in sneak_grow_overpowered

- programs/building/README.md
- programs/libraries/README.md
Does that, basically adds links as they were added to `survival` a while ago.
> Format `README` of `building` and `libraries` folders like `survival`'s

- programs/utilities/README.md
Adds a `README` to the `utilities` folder.
Feel free to directly push changes if you know more about an app! Especially as I don't know about many.
Split from #289 given that show has been stopped since creation.
> Add `README` to `utilities` section

- programs/survival/portalorient.sc
I swear English is my first language.
> "fewer", not "less"

- programs/survival/README.md
- programs/survival/combine_xp_orbs.sc
- programs/survival/flippin_cactus.sc
- programs/survival/item_holding_mobs_despawn.sc
- programs/survival/show_bees_count.sc
- programs/survival/showbiome.sc
Fixes #360 
Some of the app names were formatted incorrectly, others were missing altogether, all are now updated.
> Missing readme apps

- .github/README.md
Scarpet support for Kate <https://github.com/FedericoCarboni/kate-scarpet>
> Added link in the readme to Kate Editor support

- programs/survival/silk_spawners.sc
> Update silk_spawners.sc to 1.21.1

- programs/utilities/keepalive.sc
Moved startup to a task which allows players to load on server startup again.
https://github.com/gnembon/scarpet/issues/408
> fix: keepalive.sc - moved startup to a task

- programs/survival/horse_stats.sc
`horse.jump_strength` was renamed to `generic.jump_strength`, however the script was still broken
> Fix horse_stats.sc
