gnembon/scarpet

programs/survival/signs_for_water_streams.sc
cos when testing in survival world I placed a bunch of signs in a mobfarm, then I updated the slot by clicking on it randomly and all my signs came back. This also happened when getting my items back after dying, they popped into existence and went into my inventory, so I basically placed the same signs three times before realising exactly what was happening.
=> removed sign from inventory

README.md
Heck, you could just move the scarpet apps to the fabric-carpet repo to save yourself some work. Just put the programs directory next to the docs, or even better, just rename the docs folder to scarpet, and then rename the internal one from scarpet to docs, and next to it put the programs directory from here, saving yourself a lot of work going back and forth.
You should just make the readme a wiki page. In fact, lemme do that
=> i dont even know if this is necessary.

programs/survival/silk_spawners.sc
Netherite and diamond pickaxes are allowed to mine a spawner.
Does not unload on startup.
=> Update silk_spawners to 1.16

README.md
Added changelog for scarpet v1.7 to the README, stolen from the carpet changelog: https://github.com/gnembon/fabric-carpet/releases/tag/v1.4-homebound
=> Update README.md changelog for scarpet v1.7

programs/survival/cam.sc
'within 32 blocks' is enough. The away isn't need.
Also added full stop/period.
=> Corrected grammar in cam.sc

programs/survival/README.md, programs/survival/angel_block.sc, programs/survival/auto_lighter.sc, programs/survival/auto_pickup.sc, programs/survival/bridge_maker.sc, programs/survival/drop_heads.sc, programs/survival/easier_renewable_sponge.sc, programs/survival/hammer.sc, programs/survival/holy_hand_grenades.sc, programs/survival/inventory_refill.sc, programs/survival/magic_doors.sc, programs/survival/prospectors_pick.sc, programs/survival/replace_inventory.sc, programs/survival/revive_coral.sc, programs/survival/shear_corals.sc, programs/survival/shulkerboxes.sc, programs/survival/smasher.sc, programs/survival/sneak_grow_overpowered.sc, programs/survival/speed.sc, programs/survival/veinminer.sc, programs/survival/very_basic_overworld_wither_cage_finder.sc, programs/survival/villager_poi.sc, programs/survival/vortex_effect.sc, programs/survival/world_map.sc
Since survival programs and meant to be used in normal gameplay, they should stay loaded on server/world restart. Therefore I added __config -> (m(l('stay_loaded','true')); to all the programs, keeping scope where implemented.
=> Added stay loaded to all survival programs

programs/survival/shulkerboxes.sc
Hi,
I added another feature to shulkerboxes that I found myself wanting to have. I thought I could share it since it only adds features and doesn't change any original behavior. Feel free to reject it if you want to keep the functionality simple 🙂
**The problem**
After playing around with shulkerboxes.sc on my server I had one problem. Before I installed the app I always kept one item in the shulkerbox when taking out items. This makes it easier to shift-click in items again but also refill it either manually or automatically. I also know what has been in the shulkerbox (for example my different redstone boxes) so I can't forget one component when refilling.
**Solution**
I added the ability to write `restock keep` or `swap keep` which has the same functionality as `same` but always makes …
=> Shulkerboxes: Add ability to keep one item of each stack when restocking/swapping

programs/survival/README.md, programs/survival/nopickup.sc
App that allows players to blacklist items that they do not want to pick up from the ground. Prevents unwanted items like rotten flesh from taking up precious inventory space.
=> Add survival/nopickup.sc

programs/survival/shulkerboxes.sc
Fixes #155 
Switched places of "keep" and "same" to be consistent with the order of the detailed description.
=> Add documentation for "keep"

programs/survival/shulkerboxes.sc
When only partial of the picked up stack can be inserted into a shulkerbox, it duplicates part of the stack.
1. Name a shulkerbox `vacuum`
1. Place 1 cobblestone in the shulkerbox
1. Pickup the shulkerbox.
1. Throw 64 cobblestone on the ground.
The vacuum shulkerbox now contains 64 cobblestone and you also have 64 cobblestone in your inventory.
The vacuum shulkerbox contains 64 cobblestone and you pickup 1 cobblestone.
- Minecraft 1.16.4
- fabric-api-0.25.4+1.16
- fabric-carpet-1.16.4-1.4.16+v201105
I ran `print(actual_left);` just before the removed if. It was never 0. Maybe the magic hack stopped working?
=> Fix vacuum duplication when not all items are inserted

programs/survival/signs_for_water_streams.sc
signs_for_water_streams: fix a duplication bug when using signs from offhand.
Item in mainhand would get duplicated when using a sign from offhand. 
Fix is to detect if using offhand, and update the item count for slot '40' instead of the mainhand.
Is there a way to do it without using '40' as a magic value?
=> signs_for_water_streams: fix a duplication bug when using signs fron offhand

programs/survival/world_map.sc
By leaving the old line, it should still work in earlier versions.
=> witch_hut became swamp_hut sometime during 1.16.x

.github/ISSUE_TEMPLATE/app-suggestion.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/question.md
This PR adds two (technically three) issue templates, one for bug reports, basically using the default Github template a bit adapted, one for app suggestions, with the enhancement default from Github, and a blank one for questions. It also keeps the possibility to create blank issues, and a link to tell people to create issues about Scarpet language bugs and feature requests to the Carpet repo.
The issues also get automagically labelled to their respective labels.
You can test them in my fork: https://github.com/altrisi/scarpet/issues/new/choose
Please suggest changes if you don't like something about them or have something to improve. I just slightly changed the defaults.
=> Add issue templates

programs/survival/storage_drawers.sc
Fixes #186.
- Removes usages of `__on_tick_nether` and `__on_tick_end` and changes them to the current `__on_tick(in_dimension('...',...))`
- As a bonus, this should also now work for non-vanilla dimensions by just specifying them in the list
- Removes useless things from the `__config`
- Imports `distance_sq` from Carpet's `math` library instead of recreating it
- It seems it also adds the newline at the end. Didn't know it wasn't there, it's nice that it got added automatically
- Oh, and it also removes calling `__on_start()` since that is now done by Carpet (same way since it's global), else would be called twice
I didn't touch the command system since it's basically the root command. Also didn't upgrade anything else because just in case, since I'm not familiar with the app and I …
=> Upgrade deprecated usages in storage drawers

programs/survival/README.md, programs/survival/waypoints.sc
This app adds server-side waypoints for communal servers, where farms and POIs are of common interest to all players. Players can teleport to waypoints, if allowed (persmissions are highly customizable), or have a line render point to the selected waypoint.
The main functionality of the app can be seen here: https://youtu.be/OF_hY1sTRYY
The direction hinting is here: https://youtu.be/0N2qVahMD7s
=> Adding Waypoints app

programs/survival/README.md
I think having the name of the app in the list (in the readme) be a link to the actual app can make it easier to shop for apps, rather than scrolling trough the list and then back up to the files.
=> Adding hyperlinks to apps in the readmes

programs/survival/nether_poi.sc
replaces deprecated  '__on_tick_nether()' function call with the updated 'in_dimension()' call inside '__on_tick()'
=> deprecated nether tick in nether_poi.sc

programs/survival/playerme.sc
`playerme hotbar 0` no longer works with more recent versions of Carpet and `playerme hotbar 9` errors. The suggestions also hint at this mishap as well.
The integer range from the argument should instead range from 1 to 9 instead of 0 to 8.
=> A fix for `playerme` hotbar

programs/survival/README.md, programs/survival/portalorient.sc
This is a simple utility I wrote to prevent headaches when travelling through Nether portals. Makes the player always face a cardinal direction that is "out" of the portal so you don't have to spin around if you forget which way you're supposed to face for each specific portal in your world. This is accomplished by checking each side of the portal for blocks and making the player face the corresponding side(more air blocks or fewer solid blocks) depending on their setting. In the event of a tie, no side is preferred and the player will simply face their original direction.
=> Add portalorient script

programs/survival/shulkerboxes.sc
In the event that an item was a potion, as long as box mode is "same" or "keep", requires matching potion effect for item to be restocked.
=> Fixes #248 by checking for matching potion effect when item was potion

programs/survival/cam.sc
This PR updates the cam app to change a few things:
- Simplify timeout code:
Previously, there were two branches for the switch code: one if there was timeout, another one if there wasn't. This PR simplifies it by instead of scheduling to timeout+1sec, scheduling to timeout, so if it's 0 it will run instantly (0*20 = 0). This also brings the next upgrade:
- Fix timeout not showing directly on command output and being +1:
Until now timeout messages were sent since one second after the command was ran, which not only could make users wonder if it didn't work, but also made the timeout effectively one extra second.
- Remove empty chat messages:
At some point, quite long ago, it was changed that in command functions, if they return an empty string they would send it to chat. Previously …
=> Update Cam: Actionbar instead of chat, simplify and fix timeout

programs/survival/cam.sc
When force-gamemode is on, the server puts a player that logged out in camera mode into survival mode when loggin in. this of course breaks things. A simple check should fix that.
=> Fix for case where force-gamemode is on

programs/utilities/flower.sc
* Added support for 1.18 (still works for pre-1.18 versions)
* Now uses tasks to not freeze the game while placing blocks
* Added a count command that counts the number of flower in a given area
* Now requires OP to fill blocks
* Added settings:
* ignore_biome - doesn't check for flower forest biome when filling/counting
* glass_mode - places glass blocks instead of flowers (mainly for showing 3D areas)
* place_air_above - place air above flowers (only when glass_mode is false)
=> Updated and improved flower.sc

programs/survival/no_useless_llamas.sc
Turns out llama's and trader_llama's are different entities types.
=> Add support for trader llamas to `no_useless_llamas`

programs/survival/README.md, programs/survival/enchanting_table_bottling.sc
Shift right-click on an enchanting table with an empty glass bottle and get a bottle o' enchanting. Average xp gain from bottles is 7, so I set the cost for bottling at 8.
=> Add experience bottling through enchanting table

programs/utilities/stat.sc
* Completely rewrote almost all the code from scratch in order to improve performance and eliminate bugs.
* Cross-version compatibility: the app works in 1.16, 1.17 and 1.18.
* Added new dig types. The available ones currently are: `combined_blocks` (default; sum of all blocks mined), `total` (sum of all tool uses) and types for each kind of tool (`pick`, `pickshovel`, `shovel`, `axe`, `hoe`). Unlike `total`, `combined_blocks` counts blocks you destroyed by hand and can't be cheated by punching entities with a tool. The default dig type can be changed with `/stat settings default_dig`.
* Statistics for whitelisted offline players are now available for all dig categories (can be disabled with `/stat settings offline_digs`).
* A convenient dig display is now visible in the tablist (it won't …
=> Stat script revamp

.gitattributes
Currently only `.sc` files are highlighted. This makes `.scl` files be highlighted as well, given there's some coming in other PRs.
=> Use python's highlighter for libraries as well

programs/utilities/geode_projection.sc
This adds a simple utility app that will help you when designing flying machine based amethyst shard farms, as shown by mango in this video: https://www.youtube.com/watch?v=fY90xF3ug84
It will simply project the budding amethist blocks into the three positive sides of a box that encases the selected geode. It will then mark those blocks with one colour and mark the neoughbouring ones (the ones that should have the flying machines) in another colour. It also provides two utility functions: `clear`, to clear an area of everything _but_ budding amethyst blocks; and `place`, to place the pattern of glazed terracotta and some other block, in case you find it easier to follow blocks than holograms.
Short shocase here: https://youtu.be/pcX7-XCgBxA
=> Add geode projection app

programs/survival/sleep_ignore_fake_players.sc
Fixes #241 
Using `weather('clear', round(rand(0x7FFFFFFF))` instead of `run('weather clear')` which always does 5 minutes (or 6000 ticks)
=> Properly setting clear weather in sleep_ignore_fake_players.sc

programs/survival/item_holding_mobs_despawn.sc
Fixes #358.
Also removes the `rule` suffix in the name to prevent confusion with it being a Carpet rule, though let me know if I should revert that. It has no `README` entry so it doesn't need to be updated (adding missing entries to readme can be fixed later).
=> Fix deprecated usage in `item_holding_mobs_despawn`

programs/survival/light_level_overlay.sc
Line 92: shift the position to analyze up one block to...
Line 96: ...print the label on top of the block, not in the block
Line 97: ...get the light on top of the block, not in the block
Line 100: ...set the text color, again, based on the light on top of the block, not in the block
Upon further review, I might just dm suggestions since I don't know what I thought making a pull would do except, well, make one in the scarpet repo. Whoops!
=> Use air block above traced block to draw and color light level numbers

programs/building/curves.sc
The first 28 lines of `curves.sc` had lots of excessive indentation in object definitions; this indentation is now reduced to a single tab character per line.
=> Remove excess indentation in `curves.sc`

programs/survival/cam.sc
In 1.20.4 carpet it seems that a /tp command will override any entity pos update done in the same execution regardless of the order of the tp and pos update.
As a workaround update the position of the player in the world switching /tp instead of first switching worlds with a /tp and then position by a pos update.
This fixes #377
=> pos update / tp interference workaround

programs/survival/shulkerboxes.sc
the result of `parse_nbt` cannot be accessed with `:'text'` anymore
I tested with the following versions, and the change to the app appears backward compatible:
| Version | without PR | with PR |
|---------|--------------|---------|
| 1.20.4+carpet/1.4.128 |❌(script has no effect)|✅|
| 1.19.4+carpet/1.4.101 |✅|✅|
| 1.16.5+carpet/1.4.44 |✅|✅| 
| 1.15.2+carpet/1.4.8 |❌(script has syntax error)|❔|
=> Fix shulkerboxes.sc for minecraft 1.20.4

programs/survival/auto_lighter.sc
Updates auto_lighter to check for version, and appropriately use Enchantments (<1.21) vs components (v1.21+) depending on version.
Corrective snipped merged from @YageGeng in #395 
Fixes #395 
Fixes #405 
Fixes #406
=> Update auto_lighter.sc for v1.21

programs/survival/instamine_deepslate.sc
Updated the survival/instamine_deepslate.sc script for compatibility with the new 1.21 data components.
The file was also formatted using the Scarpet Formatter VS Code extension.
=> Update instamine_deepslate.sc for 1.21 data components

programs/survival/insomniafix.sc
A while back I wrote a script to make phantoms less annoying and I think it could be useful to other.
As of now the app contains the following bug fixes and changes for phantoms spawning:
- Phantoms no longer spawn for creative mode players (fixes MC-145177).
- Phantoms no longer spawn when the mobcap is saturated.
- Phantoms no longer spawn on mushroom islands and the void (fixes MC-126778 and MC-127599).
- Optionally fix MC-154372 reverting phantom damage to 6 hearts instead of 2.
- Optionally enable large phantom spawning which increases the size of phantoms the longer you go without sleeping. Similar to VanillaTweaks' large phantoms datapack.
All these can be configured individually with the `/insomniafix` command.
The app works by disabling phantom spawning and reimplementing it from …
=> Add insomniafix app with fixes for phantoms

programs/utilities/spellbook.sc
The vanilla /give command syntax changed. Running "/spellbook [book] give" results in no book and "[]" printed in chat.
Tested fix on 1.20.6.
=> Fix spellbook.sc give command not giving a book.

programs/survival/cam.sc
Fixes #318 by displaying an error message if you try to use the command while in creative mode. The message might not be perfect, feel free to comment on it
=> Added creative mode error message to cam.sc
